_commit: v0.4.1
_src_path: https://github.com/will-rice/papers-template.git
project_name: Lipsync Papers
project_slug: lipsync-papers
template_version: 0.1.0
topic_description: Papers related to lipsync.
