backfill:
  arxiv:
    continuation: null
    covered_from: '1991-08-01T00:00:00Z'
  huggingface:
    continuation: null
    covered_from: '2023-05-04T00:00:00Z'
continuations: {}
failures:
  arxiv:2309.07125:
  - error: 'conversion input network failure: https://arxiv.org/pdf/2309.07125'
    occurred_at: '2026-09-30T18:08:33.270565Z'
