"""Lipsync relevance gate ported from the legacy fetcher.

A paper is accepted when its title or abstract contains no negative keyword,
at least one lipsync relevance keyword, and at least one ML keyword. Matching
is case-insensitive substring matching, as in the legacy fetcher.
"""

from papers_pipeline.models import Paper
from papers_pipeline.topics import TopicDecision


NEGATIVE_KEYWORDS = (
    "speech recognition",
    "power synchronization",
    "grid-forming",
    "electric load",
    "spacecraft",
    "tractor engine",
    "audio encryption",
    "audio steganography",
    "job-shop scheduling",
    "mechanical system",
    "warp-knitted",
    "integrated sensing and communication",
    "rate-splitting",
    "reconfigurable intelligent surface",
    "spread spectrum",
    "spectrum access",
    "radiation field reconstruction",
    "wireless human gesture",
    "programmable data-plane",
    "indoor positioning",
    "near-field positioning",
    "human-drone",
    "temporal knowledge graph",
    "event localization",
    "audio backdoor",
    "forensic speaker",
    "intrusion detection",
    "nanostructure",
    "quantum neural",
    "pde solver",
    "printed memristor",
    "sonar",
    "cleft lip",
    "rhinoplasty",
    "head and neck cancer",
    "alveolar bone",
    "lip balm",
    "lip-ms",
    "transcranial",
    "alzheimer",
    "polycystic ovary",
    "diabetes mellitus",
    "perinatal",
    "dentofacial",
    "stuttering",
    "oral health",
    "face-to-face stacking",
    "talking therapies",
    "talking therapy",
    "autocratic leadership",
    "cloud cost",
    "professional wrestling",
    "respondent-driven",
    "partisan",
    "macaque",
    "ai companion chatbot",
    "immersive analytics",
    "audio description text",
    "audio hallucination",
    "audio language model",
    "membership inference attack",
    "binaural audio",
    "spatial audio",
    "sound field interpolation",
    "audio transfer learning",
    "audio pre-training",
    "audio captioning",
    "resting-state fmri",
    "granger causality",
    "speech neuroprosthesis",
    "neural speech tracking",
    "cochlear implant",
    "mmwave radar",
    "lidar-camera",
    "network twin",
    "machine translation",
    "grammar error correction",
    "named entity recognition",
    "video quality assessment",
    "scene dynamics compression",
    "video object insertion",
    "hand object interaction",
    "road damage",
    "music-driven dance",
    "dietary action",
    "active acoustic sensing",
    "talking-heads attention",
    "inter-layer communication",
    "audio-visual scene classification",
    "area threat identification",
    "pedagogical agent",
    "empathetic chatbot",
    "multimodal biometric database",
    "tiktok",
    "street video",
    "sign language detection",
    "chinese sign language",
    "sentiment analysis",
    "video motion transfer",
    "structured pruning u-net",
    "scene2audio",
    "image and layout editing",
    "body pose estimation",
    "android robot head",
    "embodied conversational agent",
    "text-audio steganography",
    "joint steganography",
    "reference audio-visual segmentation",
    "multi-view stereo",
    "lip augmentation",
    "lip filler",
    "dermal filler",
    "lip flip",
    "lip eversion",
    "lip gloss",
    "lip defect",
    "hyaluronic acid",
    "herpes labialis",
    "trigeminal neuralgia",
    "li-ion battery",
    "li-ion cell",
    "vocal biomarker",
    "speech quality assessment",
    "speech codec",
    "speech transmission",
    "speaker naming",
    "text-to-speech for",
    "lip cream",
    "asoka flower",
    "organising for change",
    "audio-vestibular dysfunction",
    "vestibular dysfunction",
    "meniere",
    "machine fault detection",
    "cold extrusion of gears",
    "medical imaging slide-lecture",
    "injection molding",
    "business intelligence course",
    "ai interview assistant",
    "facial recognition attendance system",
    "predicting face orientation",
    "classroom talk",
    "communicative learning",
    "culturally responsive leadership",
    "assistive technology for",
    "cognitive behavioral therapy",
    "cognitive training",
    "collective conversations",
    "service quality shapes",
    "construction services",
    "institutional positions",
    "fluidic camming",
    "cu-nb conductor",
    "rip current",
    "underwater acoustic",
    "lip shock",
    "cyclic loading",
    "industrial sustainability",
    "flaxseed oil",
    "emulsion stabilized",
    "morris-lecar",
    "icg-lip",
    "nfc-integrated clothing",
    "privacy filtering",
    "multimodal privacy",
    "face sketch recognition",
    "audiogen-omni",
    "translating humour",
    "translation studies",
    "audiovisual translation",
    "moderating role",
    "child temperament",
    "parental distress",
    "social-emotional functioning",
    "inter-brain synchronization",
    "consecutive interpreting",
    "masked priming",
    "ethnocultural",
    "memory work",
    "cultural tourism",
    "fire weather",
    "land policy",
    "student discipline",
    "antitrust",
    "intellectual humility",
    "cinema studies",
    "quantum error correction",
    "kuramoto",
    "riemannian manifold",
    "fault-tolerant quantum",
    "lithium-ion battery",
    "cathode material",
    "synchrophasor",
    "grid synchronization",
    "heating system",
    "coal mine",
    "iot clock",
    "wireless timer synchronization",
    "nb-iot",
    "backscatter communication",
    "massive mimo",
    "downlink power control",
    "modulation classification",
    "6g wireless",
    "ambient backscatter",
    "multiplex network",
    "turbine blade",
    "glulam",
    "membrane water treatment",
    "venous lake",
    "co2 laser",
    "hepatic encephalopathy",
    "wearable respiratory",
    "squamous cell carcinoma",
    "primate conservation",
    "corporate social responsibility",
    "circular business",
    "circular economy",
    "esg facade",
    "smart logistics",
    "offshore maintenance",
    "women entrepreneur",
    "workforce productivity",
    "business english",
    "working children",
    "digital learning",
    "hyperspectral",
    "drug toxicity",
    "tiny object detection",
    "postural control",
    "quantum convolutional",
    "partial label learning",
    "plug-and-play image restoration",
    "cryptanalytic extraction",
    "sobolev",
    "icann 2025",
    "iwann 2025",
    "isnn 2025",
    "traffic congestion",
    "fashion try-on",
    "virtual wardrobe",
    "exam proctoring",
    "construction safety",
    "placement assistance",
    "herb-symptom",
    "conversational ai coach",
    "smart glasses",
)

RELEVANCE_KEYWORDS = (
    "lip sync",
    "lipsync",
    "lip synchronization",
    "lip-synchronization",
    "lip-synced",
    "lip movement",
    "talking head",
    "talking face",
    "talking avatar",
    "speech-driven face",
    "audio-driven face",
    "audio-driven talking",
    "visual dubbing",
    "neural dubbing",
    "movie dubbing",
    "face reenactment",
    "facial reenactment",
    "facial animation",
    "visual speech",
    "real-time digital human",
)

ML_KEYWORDS = (
    "machine learning",
    "deep learning",
    "neural",
    "neural network",
    "vision-language",
    "computer vision",
    "transformer",
    "diffusion",
    "gan",
    "generative",
    "self-supervised",
    "multimodal",
    "learning-based",
)


def accept_topic(paper: Paper) -> TopicDecision:
    """Accept lipsync ML papers that avoid every negative keyword.

    Args:
        paper: Candidate paper from any adapter.

    Returns:
        The accept or reject decision with the reason.
    """
    text = f"{paper.title} {paper.abstract}".casefold()
    for keyword in NEGATIVE_KEYWORDS:
        if keyword in text:
            return TopicDecision(False, f"matched excluded term: {keyword}")
    if not any(keyword in text for keyword in RELEVANCE_KEYWORDS):
        return TopicDecision(False, "missing lipsync relevance keyword")
    if not any(keyword in text for keyword in ML_KEYWORDS):
        return TopicDecision(False, "missing ML keyword")
    return TopicDecision(True, "accepted")
